trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  backendPath: 'FlaskProject'
  frontendPath: '.'

steps:
# Backend Setup
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'

- script: |
    python -m pip install --upgrade pip
    pip install -r $(backendPath)/requirements.txt
  displayName: 'Install Python dependencies'

- script: |
    python $(backendPath)/test.py
  displayName: 'Run Backend Tests'

# Frontend Setup
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  workingDirectory: $(frontendPath)
  displayName: 'Install Frontend dependencies'

- script: |
    npm run build
  workingDirectory: $(frontendPath)
  displayName: 'Build Frontend'

# Optional: Publish Artifact
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'dist'
    artifactName: 'frontend-dist'
    condition: succeeded()

